name: Trivy Vulnerability Scanner

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - "release/**"
  pull_request:

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.50.0

      - name: Run Trivy vulnerability scanner on uv.lock
        run: |
          trivy fs uv.lock -d --format sarif --output trivy-results.sarif \
            --scanners vuln \
            --dependency-tree \
            --severity CRITICAL,HIGH,MEDIUM

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
          category: "Trivy Vulnerability Scan"
